"""Rendering a corpus into something a model can read.

The output is markdown with YAML front matter, because the reader this is built
for is an assistant being pointed at a directory. That reader needs three things
and nothing else: a stable id to refer to a segment by, the source file so a
claim can be traced back, and enough title to decide whether to open it.

Everything here is a pure function of the corpus. No clock, no ordering that
depends on filesystem iteration, no absolute paths. Two runs over an unchanged
folder produce byte-identical output, which is what makes the index safe to
regenerate and readable as a diff.
"""

from __future__ import annotations

from pathlib import Path, PurePosixPath

from .corpus import Entry, Note, entries_of, sources_by_id
from .identity import Duplicate

#: How much of a segment goes in the index before it is worth opening the file.
PREVIEW_CHARS = 240


def relative(path: Path, root: Path) -> str:
    """`path` relative to `root`, with forward slashes.

    Always POSIX-style. A Windows-shaped path in the output would make the index
    differ between machines for no reason, and the index is meant to be
    committed.
    """
    try:
        return PurePosixPath(path.relative_to(root).as_posix()).as_posix()
    except ValueError:
        return PurePosixPath(path.as_posix()).as_posix()


def preview(text: str, limit: int = PREVIEW_CHARS) -> str:
    """A single-line opening of `text`, collapsed and cut on a word boundary."""
    flat = " ".join(text.split())
    if len(flat) <= limit:
        return flat
    cut = flat[:limit]
    if " " in cut:
        cut = cut[: cut.rindex(" ")]
    return cut + "..."


def render_index(
    notes: list[Note],
    root: Path,
    duplicates: list[Duplicate] | None = None,
) -> str:
    """The top-level `INDEX.md`."""
    entries = entries_of(notes)
    sources = sources_by_id(notes)
    lines: list[str] = [
        "<!-- Generated by notelocus. Regenerate rather than edit. -->",
        "# Notes index",
        "",
        f"{len(entries)} ideas across {len(notes)} files.",
        "",
        "Each idea has a stable id derived from its content, so it keeps that id",
        "across regenerations and can be referred to from outside this file.",
        "",
    ]

    repeated = {sid: paths for sid, paths in sources.items() if len(paths) > 1}
    if repeated:
        lines += [
            f"**{len(repeated)} ideas appear in more than one file**, byte for byte after",
            "normalisation. They are listed once below, with every source.",
            "",
        ]

    if duplicates:
        lines += [
            f"**{len(duplicates)} pairs are near-duplicates** — not identical, but close",
            "enough to be the same thought written twice. See `DUPLICATES.md`.",
            "",
        ]

    by_file: dict[str, list[Entry]] = {}
    for note in notes:
        by_file.setdefault(relative(note.path, root), []).extend(note.segments)

    lines += ["## By file", ""]
    for path in sorted(by_file):
        found = by_file[path]
        lines.append(f"### `{path}`")
        lines.append("")
        for entry in found:
            where = sources.get(entry.id, [])
            also = ""
            if len(where) > 1:
                others = [relative(p, root) for p in where if relative(p, root) != path]
                also = f" — also in {', '.join(f'`{o}`' for o in sorted(others))}"
            lines.append(f"- **`{entry.id}`** {entry.title}{also}")
            if body := preview(entry.segment.body):
                lines.append(f"  - {body}")
        lines.append("")

    tagged = _by_tag(notes)
    if tagged:
        lines += ["## By tag", ""]
        for tag in sorted(tagged):
            ids = " ".join(f"`{i}`" for i in sorted(tagged[tag]))
            lines.append(f"- **#{tag}** — {ids}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _by_tag(notes: list[Note]) -> dict[str, set[str]]:
    out: dict[str, set[str]] = {}
    for note in notes:
        for entry in note.segments:
            for tag in entry.segment.tags:
                out.setdefault(tag, set()).add(entry.id)
    return out


def render_duplicates(duplicates: list[Duplicate], entries: dict[str, Entry], root: Path) -> str:
    """`DUPLICATES.md` — pairs that look like the same idea twice.

    Reported, never acted on. Deciding that two notes are the same thing is a
    judgement about meaning, and this file exists so a person can make it with
    the evidence in front of them.
    """
    lines = [
        "<!-- Generated by notelocus. Regenerate rather than edit. -->",
        "# Near-duplicates",
        "",
        f"{len(duplicates)} pairs above the similarity threshold.",
        "",
        "Similarity is Jaccard over word shingles of normalised text: it measures",
        "wording, not meaning. A high score means the same words in the same order,",
        "which is usually the same idea pasted twice and occasionally two different",
        "ideas expressed identically. Nothing here has been merged or removed.",
        "",
    ]
    for dup in duplicates:
        left, right = entries.get(dup.left), entries.get(dup.right)
        if not left or not right:
            continue
        lines += [
            f"## {dup.score:.2f} — `{dup.left}` and `{dup.right}`",
            "",
            f"- `{dup.left}` in `{relative(left.source, root)}` — {left.title}",
            f"- `{dup.right}` in `{relative(right.source, root)}` — {right.title}",
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_segment(entry: Entry, root: Path, also_in: list[Path]) -> str:
    """One segment as a standalone document with front matter."""
    sources = sorted({relative(p, root) for p in [entry.source, *also_in]})
    front = [
        "---",
        f"id: {entry.id}",
        f"title: {_yaml_scalar(entry.title)}",
        f"modified: {entry.modified.date().isoformat()}",
        f"split: {entry.segment.strategy}",
        f"line: {entry.segment.start_line}",
        "sources:",
        *[f"  - {s}" for s in sources],
    ]
    if entry.segment.tags:
        front += ["tags:", *[f"  - {t}" for t in entry.segment.tags]]
    front.append("---")
    return "\n".join([*front, "", f"# {entry.title}", "", entry.segment.body.strip(), ""])


def _yaml_scalar(text: str) -> str:
    """Quote a title so it survives YAML.

    Titles come from arbitrary pasted text and routinely contain colons, hashes
    and quotes. Single-quoted YAML needs only one escape - a literal quote is
    doubled - where double-quoted style would also need backslash handling for
    every control character pasted text might carry.
    """
    return "'" + text.replace("'", "''") + "'"
